### ISSUE TITLE
[feat] 운전주행 상태를 감지하기

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#17]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
<img width="606" alt="스크린샷 2023-07-13 오후 6 15 12" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/d1bda95c-e13c-43c7-b800-ec492b2ab05a">

# TODO
- [x] automotive 적용해보기
- [x] background, inactive 상태일때도 automotive 변화 감지시 동작하도록 → 현재는 automotive, cycling, walking, stationary 상태에서도 뜨도록 했어요 (백그라운드 + 노티 테스트하려고)
- [ ] 앱을 자동으로 실행시킬 수 있을까?
- [ ] 안된다면 shortcut 고려
---
- [x] Extension 폴더 따로 빼두었습니다
