### ISSUE TITLE
[feat] 속도 데이터 계산 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#19]
#  Description
유의미한 속도 데이터를 뽑아내는 것이 목표입니다. 

# TODO
- [x] 속도를 핸들링하기 위한 `LocationsHandler` 타입 생성
- [x] CLLocation에서 제공하는 raw 데이터를 인식하기에 적합한 정보로 변경 
- [x] 속도 데이터의 정확성을 소숫점 첫번째 자리까지 높이기
- [x] Background 상태에서도 CoreLocation이 끊기지 않도록 설정 

# Additional
- [x] AppGroup 적용(원래 적용되었어야 했는데 여기서 추가함)

# 참고자료 
- [notion](https://www.notion.so/km-h-109abaf0991e4efb8fe69774368231a2?pvs=4)
