### ISSUE TITLE
[feat] 차선 변경 인지

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#23]
#  Description
- 차선 변경을 인지

# TODO
- [ ] Research 어떤 로직을 사용해야 차선 변경을 감지할 수 있을지 알아보기
- [ ] 차선 변경과 좌회전 우회전을 어떻게 구분할 수 있을지 알아보기
- [ ] LocationHandler에 관련 로직 추가하기

**Comment by Damagucci-Juice** [comment]
기능이 디자인적으로 어떻게 표현될지에 대한 구체적인 방향성이 느껴지지 않아서 작업 종료하고 이슈 닫겠습니다.
