### ISSUE TITLE
[feat] 이착륙시 배경변화와 애니메이션 변화주기

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#26]
#  Description
@pppineappple 이 작업해준 배경 뷰를 이용해서 비행기의 이착륙을 도와주는 기능을 넣을게요. 

# TODO
- [ ] motion status에 따른 배경 뷰 변화
- [ ] 이미지 소스 Assets.asset에 추가

### Start 상태
- [ ] start 버튼을 누르기전엔 정지상태 구현
- [ ] 5초간 직진
- [ ] 5초에 1초 동안 상승
- [ ] Normal 상태로 전환

### Normal 상태
- [ ] Acceleration Update
- [ ] 비정상 상황 반응하면 abnormal로 전환

### Abnormal 상태
- [ ] 기체 좌우로 빠르게 흔들기
- [ ] 2초 후에 normal 로 상태 전환

### Finish 상태
- [ ] 3초 쯤에 3초에 걸쳐 하강
- [ ] (나중)분석뷰로 넘김
- [ ] Acceleration Stop, Location Stop
- [ ] 6초 부분에 정지(관제탑 부근)
