### ISSUE TITLE
[feat] 다이나믹 아일랜드 애니메이션 적용

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#27]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
텍스트 바꾸는 것처럼 이미지 이름을 timestamp를 카운팅해주는 방식

# TODO
- [x] https://github.com/simonberner/ladi-simulator 여기 코드 참고해서 만들어봅니다
- [x] 이미지 이름 string interpolation으로 타이머 카운팅될 때마다 이미지도 바뀔 수 있도록
- [x] 너무 긴 struct 이름 변경 및 폴더, 디렉토리 구조 수정 작업
- [x] 급감가속 카운팅해서 다이나믹 아일랜드에 보이도록 적용
- [x] 주행상태에 따라 이미지 다르게 표시
- [x] 코드 리팩토링

**Comment by jaelyung** [comment]
주행상태에 따라 이미지 다르게 표시
- Compact Leading 완료
- Compact Trailing의 경우 timestamp % 4를 해야되는 경우가 있고, Trailing에 들어가는 이미지 name을 따로 줘야하는데 이 부분 코드 수정 고민중

**Comment by dayo2n** [comment]
close with #44
