### ISSUE TITLE
[feat] 결과뷰에서 주행 기록을 보여줍니다

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#30]
#  Description
결과 분석 창인 것 같네요 주행시간과 부주의 횟수, 차트데이터를 보여줍니다
<img width="281" alt="스크린샷 2023-07-19 오전 10 16 56" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/cf0381a2-5dcd-492e-b53d-350d65c90b53">

# TODO
- [ ] #38
- [x] 뷰 생성: 비행기(왼쪽에서 나타나는 것으로), 주행 기록
- [x] 급감가속이 찍히는 곳에 포인트
- [x] 이걸 무슨 주기로 데이터들을 써야하는지 ... 고민해봐야겠네요 .... → 일단 그냥 급감가속 감지될 때 다
- [x] 부주의 데이터
- [x] 운전 시간 .... 흠 ...
- [x] 예쁜 모양 만들기

**Comment by dayo2n** [comment]
<img width="419" alt="스크린샷 2023-07-19 오후 3 32 21" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/845d30b3-2aed-4501-82c9-72b039808219">

**Comment by dayo2n** [comment]
<img width="419" alt="스크린샷 2023-07-19 오후 3 50 35" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/cbb9d898-3c8d-429d-890a-99d6186cc5f2">

**Comment by dayo2n** [comment]
![IMG_030A05478A1C-1](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/672b7377-b588-4211-8318-22d6485b4c7f)
