### ISSUE TITLE
[feat] 주행 종료 후 주행 기록을 보여줍니다

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#31]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
결과 분석 창인 것 같네요 주행시간과 부주의 횟수만 일단 보여줍니다
<img width="281" alt="스크린샷 2023-07-19 오전 10 16 56" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/cf0381a2-5dcd-492e-b53d-350d65c90b53">

# TODO
- [ ] 운행 종료를 감지하는 로직
- [ ] 뷰 생성: 비행기(왼쪽에서 나타나는 것으로), 주행 기록
- [x] #30 가속도에 대한 차트는 이슈를 분리해서 따로 처리합니다
