### ISSUE TITLE
[fix] Team signing 문제 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#4]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

# Description
<img width="706" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/50472122/963fe91a-c66f-47ea-96a9-65c82adde632">

# 예상 해결 방안
- App Group Identifier를 개개인마다 추가해줘야하는 번거로움이 있음-> 작업 * 5
- Team Signing을 하면 그 팀계정에서 App Group Identifier를 **한번만** 생성하면 아래에 빨간 오류가 사라짐

# TODO
- [x] Team 전용 Provisioning Profile 추가
- [x] 멤버들 apple 개발자 계정을 Team Profile에 등록
- [x] App Group Identifier 새로 등록
- [x] Xcode에서 Target 2개에서 `Signing & Capabilities` 편집 
- [x] Signing Certificates 팀원들에게 AirDrop으로 전달
- [x] 멤버들 사용할 맥북 기기 연번 등록

# 참조
- [provisioning profile 생성 + 기기 추가 + 팀 초대 ](https://yesiamnahee.tistory.com/185)

**Comment by dayo2n** [comment]
오늘 핸즈온세션 성공적으로 마쳤으니 클로즈하겠습니다~~
