### ISSUE TITLE
[refactor] 이미지 이름, 텍스트, 컬러코드 상수화 및 Localizing

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#51]
#  Description
작년 1기분 프로젝트 중 참고하기 좋은 플젝이 있어서 요기 [소스](https://github.com/HRHN-HaruHana/HRHN-iOS)와 구글링 참고해서 수정합니다

# TODO
- [x] Localizable.strings 추가하면서 Sources, Resources 폴더 추가 및 파일 이동
- [x] 컬러코드는 Color+Extension.swift에
- [x] contents 텍스트들 로컬라이징
- [x] DriveSimulator의 status to Enum
- [x] 우연히 다이나믹아일랜드에서 초반 이미지가 보이지 않던 부분 수정
- [x] 영어 localizing
