### ISSUE TITLE
[refactor] DrivePalView 안에서 모델 분리 + 더 작은 뷰로 나누기

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#53]
# 👟 Description
`DrivePalView`가 300줄이 넘어갔습니다. Body만 해도 벌써 200줄이 넘어가는 Massive한 `View`가 되어가고 있어요. 
가만 두고 볼 수 없죠. 리펙토링으로 조사버리겠습니다. 

# ✅ TODO
- [x] 기능 단위로 DrivePalView 분석
- [x] `View` 단위로 DrivePalView 분석
  - 배경뷰, 비행기뷰로 나누기 
- [x] 각각의 View에 맞는 모델 나누기
- [x] CoreLocation과 CoreMotion을 핸들링을 어떻게 할지 팀원과 고민
