### ISSUE TITLE
[feat] 주행 상태를 보여주는 메인뷰 UI 구현

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#6]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
<img width="872" alt="스크린샷 2023-07-11 오후 10 24 12" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/9d52bf1c-fc2b-4017-ac89-71ae8bef5efa">

# TODO
- [x] SKScene에서 시간에 따라 우에서 좌로 움직이는 배경씬: BackgroundScene
- [x] 배경씬과 비행기를 담는 View: DrivingPalView
- [x] ~~구찌의 네이밍 룰 확인해서 파일 이름 수정하기 ex. 파일이름은 명사? 변수는 동사?~~ 구찌의 변심
- [ ] redSky 배경이미지 시작할 때 화면 width만큼 반복되는 원인찾아 해결하기
- [x] 정상 주행시에는 둥둥 떠다니는 애니메이션 + 푸른 배경, 급감가속 감지시 흔들흔들 + 붉은 배경
