### ISSUE TITLE
[feat] 주행 중 표시되는 Compact 다이나믹 아일랜드 구현

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#7]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
<img width="571" alt="스크린샷 2023-07-11 오후 10 30 51" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/61307199/32c3f2c8-b40a-4aad-a2f0-a1bdc0121fdd">

# TODO
- [x] DrivePal의 info.plist에 Supports Live Activities 추가 (Type: Boolean, Value: Yes)
- [ ] DrivePalWidgetExtension의 DrivePalWidgetExtensionLiveActivity.swift TargetMembership에 DrivePal 체크 -> XCode 충돌 현상으로 사용하지 않음
- [x] leading side에 비행기 아이콘 출력, trailing side에 부주의 횟수를 출력하는 View : CompactDynamicIslandView
