### ISSUE TITLE
[feat] 앱 화면을 개편합니다

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#72]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
<img width="556" alt="스크린샷 2023-07-31 오전 2 18 48" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/319ae3b0-c359-4b69-b14c-934d609ad0b6">

# TODO
- [x] 배경 변경
- [x] 부주의 운전시 애니메이션 변경
- [x] 비행기 이미지 변경
- [x] 비행기 애니메이션 변경
- [x] 속도 표시
- [x] 부주의시 속도 애니메이션 변경
- [x] 종료버튼 변경

**Comment by dayo2n** [comment]
@Damagucci-Juice  구찌 비행기 애니메이션에서 문제있는거 #65 에서 수정하신거 맞나요? 
(비행기가 낮게 날고있음 + DrivingPalView내 조건문에서 .none을 포함하지 않아서 takingOff에 대한 액션이 씹히던 버그)
맞다면 어차피 저 피알이 나아아중에 합쳐질거니까 비행기 관련 버그 여기서 수정해주실 수 있나여?
비행기 애니메이션하려다가 넘 졸려서 뒤를 부탁합니다 ~.~

**Comment by Damagucci-Juice** [comment]
> @Damagucci-Juice 구찌 비행기 애니메이션에서 문제있는거 #65 에서 수정하신거 맞나요?
> (비행기가 낮게 날고있음 + DrivingPalView내 조건문에서 .none을 포함하지 않아서 takingOff에 대한 액션이 씹히던 버그)
> 맞다면 어차피 저 피알이 나아아중에 합쳐질거니까 비행기 관련 버그 여기서 수정해주실 수 있나여?
> 비행기 애니메이션하려다가 넘 졸려서 뒤를 부탁합니다 ~.~

알겠씁니다. 저쪽 PR에 이미 있는데 추가해서 반영할게요

**Comment by dayo2n** [comment]
비행기, 배경 에셋 변경 및 애니메이션 디테일 수정
![Simulator Screen Recording - iPhone 14 Pro - 2023-07-31 at 12 53 42](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-RockStars/assets/57654681/2ea32e28-71e6-4589-8afd-e1a1680bf3e0)
