### ISSUE TITLE
[feat] 다이나믹 아일랜드 디자인 추가 및 수정

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MC3-Team15-RockStars#84]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

#  Description
개발하려는 기능은 이런 거예요

# TODO
- [ ] compactLeading 에 사용될 이미지 추가
- [ ] 해당 부분 view 로 수정
- [ ] expanded 경고 디자인 수정
